### ISSUE TITLE
grid scores and spatial analyses

### ISSUE THREAD

**Issue by klaragerlei** [openlists/SpikeResources#1]
Hi,

Thank you for sharing this list, it's really helpful!

I have some spatial analyses to add if you think they would be useful:
- I collected different grid scores here: https://github.com/klaragerlei/grid_score
- We shared some code for analyzing spatial cells we use in the Nolan lab: https://github.com/MattNolanLab/SpatialEphysAnalysis

Best wishes,
Klara

**Comment by TomDonoghue** [comment]
These look great, thanks for suggesting them! I have added them to the list!
